version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: ["air", "-c", ".air.toml"]
    depends_on:
      - db
      - redis

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 4306:3306
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  db: